### ISSUE TITLE
OpenAL dependency

### ISSUE THREAD

**Issue by eserte** [athreef/Alien-raylib#2]
Currently the build fails on all my smoker systems, mainly because of this failure:
```
/tmpfs/.cpan-build-cpansand/2018012021/Alien-raylib-0.006-0/_alien/build_wP9P/raylib-ca921e5a53fdd3412f5f81e3a739f54d68cb63a7/src/audio.c:87:59: fatal error: AL/al.h: Datei oder Verzeichnis nicht gefunden
     #include "AL/al.h"              // OpenAL basic header
                                                           ^
compilation terminated.
```
Question: is it expected for an alien distribution to depend only on other alien-ized distributions? Or may an alien distribution depend on system packages which the user has to install himself? If the latter is the case, then probably this should be documented, in README or INSTALL. And I would make a mapping entry to `CPAN::Plugin::Sysdeps`, so my smokers are able to test your distribution.

**Comment by a3f** [comment]
Ideally, the `Alien::` package should depend only on OS and CPAN, but I shied away from alien-izing OpenGL and X11…

Thanks for telling me about `CPAN::Plugin::Sysdeps`. I've updated the [documentation here](https://github.com/athreef/Alien-raylib#system-requirements) about the Ubuntu packages needed to install it on Travis' Ubuntu image.

**Comment by a3f** [comment]
Except from the FreeBSD [port file](https://bz-attachments.freebsd.org/attachment.cgi?id=189997) [waiting](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225402) for inclusion into the ports tree: 
```
XLIB_DEPENDS=	libopenal.so:audio/openal-soft
X
XUSES=		cmake openal:al
XUSE_LDCONFIG=	yes
XUSE_XORG=	x11 sm ice xext xrandr xi xinerama xxf86vm xcursor
```

(`Alien::raylib` already takes care of CMake)

**Comment by eserte** [comment]
I think libglew-dev is not needed --- at least the module compiles & tests OK on my debian-like systems (jessie, stretch, xenial) without that one. On the other hand, libopenal-dev seems to be missing in your list.

**Comment by a3f** [comment]
I repointed the Alien distribution at a more recent commit that doesn't require OpenAL anymore. Did it not work for you? What did it fail at? I will test without `libglew-dev` on Travis and amend the documentation if need be.

**Comment by eserte** [comment]
You're right, openal is not needed.

**Comment by eserte** [comment]
On FreeBSD the test suite fails:
```
# Failed test 'xs'
# at t/init.t line 15.
#   ExtUtils::CBuilder->link failed
#     error building testalienVKHWd/test.so from testalienVKHWd/test.o at /usr/perl5.24.0p/lib/site_perl/5.24.0/ExtUtils/CBuilder/Base.pm line 331.
#     cc -L/home/eserte/.cpan/build/2018012621/Alien-raylib-0.007-0/blib/lib/auto/share/dist/Alien-raylib/lib -shared -L/usr/local/lib -fstack-protector -o testalienVKHWd/test.so testalienVKHWd/test.o -lraylib -lm -l/usr/lib/libpthread.so -l/usr/local/lib/libopenal.so -l/usr/local/lib/libSM.so -l/usr/local/lib/libICE.so -l/usr/local/lib/libX11.so -l/usr/local/lib/libXext.so -l/usr/local/lib/libXrandr.so -l/usr/local/lib/libXinerama.so -l/usr/local/lib/libXi.so -l/usr/local/lib/libXxf86vm.so -l/usr/local/lib/libXcursor.so
#     /usr/bin/ld: cannot find -l/usr/lib/libpthread.so
#     cc: error: linker command failed with exit code 1 (use -v to see invocation)
t/init.t ............... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/3 subtests 
# LIBS: -L/home/eserte/.cpan/build/2018012621/Alien-raylib-0.007-0/blib/lib/auto/share/dist/Alien-raylib/lib -lraylib
```
I am not sure if using -l on an absolute path is supported.

**Comment by a3f** [comment]
Indeed. I've fixed it upstream and tested that the tests pass on a FreeBSD VM.

**Comment by eserte** [comment]
0.008 looks now better. The only thing left is support for older OS versions (and I don't know if you want to support these):
* FreeBSD 9, sample report: http://www.cpantesters.org/cpan/report/d7cb3e34-0339-11e8-b0d1-b6c4abd39192
* CentOS 6, sample report: http://www.cpantesters.org/cpan/report/d956d128-0339-11e8-b0d1-b6c4abd39192

**Comment by a3f** [comment]
Excellent. Thanks for your assistance. C99 is a hard requirement and CMake configures the appropriate command line flag, which GCC 4.2 is supposed to support. So I don't quite understand why your first report fails… Any ideas?

I've opened a pull request upstream at GLFW and already patched it in raylib. I'll collect some bug fixes and create a new `Alien::raylib` release in the coming days.

**Comment by a3f** [comment]
Upstream doesn't depend on OpenAL anymore and Linux tests now usually pass.
